name: Metal Parser

on:
  workflow_dispatch:

jobs:
  parse:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout and run parser
      uses: actions/checkout@v4
      
    - name: Setup and run everything
      run: |
        # Устанавливаем Python
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 lxml
        
        # Создаем пустой файл
        echo '{"trimet": [], "parad": [], "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'", "status": "initial"}' > results.json
        
        # Запускаем парсер (если есть)
        if [ -f "main.py" ]; then
          python main.py || echo "Парсер завершился с ошибкой"
        else
          echo "main.py не найден, используем тестовые данные"
          echo '{
            "trimet": [
              {"name": "Арматура 6 (6 метров)", "price": 90},
              {"name": "Арматура 8 (6 метров)", "price": 160}
            ],
            "parad": [
              {"name": "Арматура 6 мм AIII 6м", "price": 88},
              {"name": "Арматура 8 мм AIII 6м", "price": 150}
            ],
            "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'",
            "status": "test_data"
          }' > results.json
        fi
        
        echo "Финальный файл:"
        ls -la results.json
        cat results.json
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: parsing-results
        path: results.json
