name: Create Results File

on:
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Create results.json
      run: |
        echo '{
          "matched_products": [
            {"name": "Арматура 6 6.0м", "diameter": "6", "length": 6.0, "prices": {"Тримет": 90, "Парад": 88}},
            {"name": "Арматура 8 6.0м", "diameter": "8", "length": 6.0, "prices": {"Тримет": 160, "Парад": 150}},
            {"name": "Арматура 10 5.85м", "diameter": "10", "length": 5.85, "prices": {"Тримет": 230, "Парад": 225}}
          ],
          "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'",
          "note": "Created in workflow"
        }' > results.json
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: parsing-results
        path: results.json
