name: Metal Products Parser

on:
  workflow_dispatch:

jobs:
  parse:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create test .env file
      run: |
        echo "TRIMET_ARMATURA_URL=https://trimet.ru/catalog/chernyy_metalloprokat/armatura_1/" > .env
        echo "PARAD_ARMATURA_URL=https://72parad.ru/metalloprokat/armatura/" >> .env
        echo "Created .env file with test URLs"
        
    - name: Run parser
      run: |
        python main.py
        
    - name: Check results
      run: |
        if [ -f "results.json" ]; then
          echo "✅ results.json created successfully"
          echo "File size: $(wc -l results.json | awk '{print $1}') lines"
          echo "First 10 lines:"
          head -n 10 results.json
        else
          echo "❌ results.json not found!"
          exit 1
        fi
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: parsing-results
        path: results.json
