name: Metal Products Parser

on:
  workflow_dispatch:

jobs:
  parse:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run parser
      run: |
        python main.py || echo "Parser failed, but continuing..."
        
    - name: Create results if missing
      run: |
        if [ ! -f "results.json" ]; then
          echo "Creating fallback results.json..."
          python -c "
import json
from datetime import datetime
data = {'error': 'Parser failed', 'timestamp': datetime.now().isoformat(), 'status': 'fallback'}
with open('results.json', 'w') as f:
    json.dump(data, f, indent=2)
          "
        fi
        
    - name: Check results
      run: |
        echo "Checking results.json..."
        ls -la results.json
        echo "File content:"
        cat results.json
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: parsing-results
        path: results.json
