name: Metal Products Parser

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  parse:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Debug environment
      run: |
        echo "Trimet URL: ${{ secrets.TRIMET_ARMATURA_URL }}"
        echo "Parad URL: ${{ secrets.PARAD_ARMATURA_URL }}"
        
    - name: Run parser
      env:
        TRIMET_ARMATURA_URL: ${{ secrets.TRIMET_ARMATURA_URL }}
        PARAD_ARMATURA_URL: ${{ secrets.PARAD_ARMATURA_URL }}
      run: |
        python main.py
        
    - name: Check if results.json exists
      run: |
        if [ -f "results.json" ]; then
          echo "results.json exists"
          ls -la results.json
          echo "First few lines:"
          head -n 10 results.json
        else
          echo "ERROR: results.json does not exist!"
          exit 1
        fi
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: parsing-results
        path: results.json
        
    - name: Commit and push results
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        if git diff --quiet --exit-code results.json; then
          echo "No changes to commit"
        else
          git add results.json
          git commit -m "🤖 Auto-update: parsing results [$(date +'%Y-%m-%d %H:%M')]"
          git push
        fi
